plugins: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety
  - rubocop-rake
  - rubocop-sequel

Rails/SkipsModelValidations:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/ClassLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolArray:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
